#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
mocap_node:
    ros__parameters:
        rigid_bodies:
            5:
                pose: "ROSinante/pose"
                odom: "ROSinante/odom"
                child_frame_id: "base_link"
                parent_frame_id: "map"
           
        optitrack_config:
                multicast_address: "239.255.42.99"
                #multicast_address: "10.22.22.192"
                command_port: 1510
                data_port: 9000
                enable_optitrack: true
